### ISSUE TITLE
Splits used to replace in quote

### ISSUE THREAD

**Issue by airpods69** [santhalakshminarayana/Quotation_Generation_Glove_LSTM_Pytorch#1]
Why would you replace the same thing with the same thing? aren't those unnecessary in this line? 

`quote = quote.replace(',', ' ,').replace('.', ' .').replace('_','').strip('\n') + ' ;'`

**Comment by santhalakshminarayana** [comment]
No. I'm adding space before "," and ".". You can choose re.sub for doing the same.
